### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by gruber76** [comment]
Should we include an `engines` line in package.json, or are we worried about the extra maintenance?

**Comment by vladikoff** [comment]
> Should we include an engines line in package.json, or are we worried about the extra maintenance?

@shama told me those cause issues in Yarn, so I shall stay away from that...

**Comment by shama** [comment]
npm used to warn on `engines` and now it doesn't for some reason. yarn will hard error on it.

**Comment by XhmikosR** [comment]
Doesn't `--ignore-engines` work in that case?

`engines` exists for this exact reason.

**Comment by shama** [comment]
`engines` _might_ help the 1 or 2 people using `yarn` to install Grunt while on an old version of Node.js.

But thinking about it, I doubt `yarn` even works on the older versions of Node.js that we would even try to warn people about. So that 1 or 2 people might actually be 0 people. To me, it's not worth the time to worry about.

**Pull request merged**
