### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@vladikoff: do we have any decision about dropping node.js 0.10 support? Otherwise this PR is wrong.

**Comment by XhmikosR** [comment]
Actually, I'd rather one of us do this change if needed.

**Comment by paladox** [comment]
Hi why close this.

**Comment by vladikoff** [comment]
we still want to support 0.10 imho. are there any usage numbers? I still use 0.10

**Comment by XhmikosR** [comment]
I agree that we shouldn't drop 0.10 support.

**Pull request closed without merging**
