### PR TITLE
When grunt 1.0.0 is released it will cause errors for everyone

### PR DESCRIPTION
**Pull request by paladox**
See https://integration.wikimedia.org/ci/job/mediawiki-core-npm-node-4.3/293/console

### CODE REVIEW

**Comment by paladox** [comment]
@vladikoff  Hi why did you close this.

**Comment by vladikoff** [comment]
"grunt": ">=0.4.0" should be fine for 1.0.0

**Comment by paladox** [comment]
@vladikoff but its failing https://integration.wikimedia.org/ci/job/mediawiki-core-npm-node-4.3/293/console

**Comment by vladikoff** [comment]
```
16:01:59 npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
16:01:59 npm ERR! peerinvalid Peer grunt-karma@0.12.1 wants grunt@0.4.x
```

These plugins need to be updated to latest versions

**Comment by paladox** [comment]
Oh thanks

**Pull request closed without merging**
