### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by vladikoff**
WIP

### CODE REVIEW

**Comment by stanlemon** [comment]
@vladikoff I know this is already merged, but just wondering if it would be possible to update jshint as well?  It seems like jshint points to an older and vulnerable version of lodash and thus when I use this plugin `npm audit` notes the vulnerability coming from grunt-contrib-jshint chain. I'm happy to submit a PR if that would be preferred. Thanks!

**Comment by vladikoff** [comment]
@stanlemon see https://github.com/jshint/jshint/pull/3283

**Comment by stanlemon** [comment]
Got it, thanks @vladikoff!

**Comment by sntran** [comment]
@vladikoff Will you be able to publish 1.2.0 to npm?

**Pull request merged**
